894 passwords feedback
tactilenews/100eyes pull request #949
Opened 2021-06-27 11:38 UTC by tillprochaska

2021-09-01 21:58 UTC, roschaefer requested changes
![looks good](https://media.giphy.com/media/WNOgDp5GrHotRFJeE7/giphy.gif?cid=ecf05e47pw0ayoh337rfnmy4honketd42m9kms5qtkvzco04&rid=giphy.gif&ct=g)

This PR already looks really good and it is ready to be merged, no?

I would like to improve the UX though. I'm getting confused by the `password` and `otp_code` inputs in the very same UI component. If we cannot put them on different pages, could we at least make a visual split between the two?

![swappy-20210901_235245](https://user-images.githubusercontent.com/2110676/131750624-2e8ec6e9-3c87-4d9b-879b-581e7b63e1b4.png)


Also, the validation error message is not quite true. The password *is* 8 characters but the `otp_code` was wrong.

2021-09-02 10:21 UTC, tillprochaska commented
> Also, the validation error message is not quite true. The password is 8 characters but the otp_code was wrong.

True! I updated the error message.

> I would like to improve the UX though. I'm getting confused by the password and otp_code inputs in the very same UI component. If we cannot put them on different pages, could we at least make a visual split between the two?

I think we should still put them on different pages given the feedback we got from editors. I have a POC for that, but I’m not 100% sure about that yet, so I’d like to do that in a separate PR.

For users that don’t have OTP enabled, the OTP field isn’t displayed. As the primary use case for password resets is onboarding of new editors (i.e. they don’t have OTP enabled yet) and given that the ideal solution is a true two-step flow, maybe we can keep it like this for now?

<img width="628" alt="Screen Shot 2021-09-02 at 12 19 59" src="https://user-images.githubusercontent.com/1512805/131827121-db6f9b73-1f28-4760-a7e3-8b9b311b5300.png">

2021-09-02 21:01 UTC, tillprochaska commented
@roschaefer Ich habe meinen Ansatz mal ein bisschen aufgeräumt und in #1035 gepusht (ab https://github.com/tactilenews/100eyes/pull/1035/commits/c66d8562789c45e470798852c98dae1437f2d1ef).

2021-09-07 07:09 UTC, roschaefer approved these changes
OK, so the changes are done via a follow-up PR? Fine for me. I'll approve.


![fine for me](https://media.giphy.com/media/DFNd1yVyRjmF2/giphy.gif?cid=ecf05e472mcfo10iwq5dsbc1rhyrd3nj0tdusscwjv87erlc&rid=giphy.gif&ct=g)

2021-09-07 07:09 UTC, merged